<?php
/** @var \OnTap\Deal\Block\Subcategories $block */
/** @var \Magento\Framework\Escaper $escaper */
$categories = $block->getCategoriesList();
$currentCategory = $block->getCurrentCategory();
$parentCategory = $currentCategory->getParentCategory();

?>
<?php
$showList = array_slice($categories, 0, 5);
$hiddenList = ((int)count($categories) !== 5) ? array_slice($categories, 5, count($categories)) : null;
?>

<?php if (!empty($categories)): ?>
<div class="faceted-navigation desktop">
    <div class="faceted-navigation-header">
        <?php if ((int) $currentCategory->getLevel() > 2): ?>
            <h1 class="faceted-navigation-current-section">
                <?= $escaper->escapeHtml($currentCategory->getName()) ?>
            </h1>
            <h5 class="faceted-navigation-category-label">
                <?= $escaper->escapeHtml(__('in %1', $parentCategory->getName())) ?>
            </h5>
        <?php endif; ?>
        <?php if ((int) $currentCategory->getLevel() === 2): ?>
            <h1 class="faceted-navigation-current-section">
                <?= $escaper->escapeHtml($currentCategory->getName()) ?>
            </h1>
        <?php endif; ?>
    </div>

    <div class="faceted-navigation-list">
        <ul class="faceted-navigation-items">
            <?php if ((int) $currentCategory->getLevel() > 2): ?>
                <li>
                    <a class="<?= ($parentCategory->getId() === $currentCategory->getId()) ? 'active': '' ?>"
                       href="<?= $escaper->escapeUrl($parentCategory->getUrl()) ?>">
                        <?= $escaper->escapeHtml(__('Ofertas de %1', $parentCategory->getName())) ?>
                    </a>
                </li>
            <?php endif; ?>
            <?php if ((int) $currentCategory->getLevel() === 2): ?>
                <li>
                    <a class="<?= ((int) $currentCategory->getLevel() === 2) ? 'active': '' ?>"
                       href="<?= $escaper->escapeUrl($currentCategory->getUrl()) ?>">
                        <?= $escaper->escapeHtml(__('Ofertas de %1', $currentCategory->getName())) ?>
                    </a>
                </li>
            <?php endif; ?>

            <?php foreach ($showList as $category): ?>
                <li>
                    <a class="<?= ($category->getId() === $currentCategory->getId()) ? 'active': '' ?>"
                       href="<?= $escaper->escapeUrl($category->getUrl()) ?>">
                        <?= $escaper->escapeHtml($category->getName()) ?>
                    </a>
                </li>
            <?php endforeach; ?>

            <?php 
				if(!empty($hiddenList)):
				if(count($hiddenList)): ?>
                <div class="toggle-container">
                    <?php foreach ($hiddenList as $category): ?>
                        <li>
                            <a class="<?= ($category->getId() === $currentCategory->getId()) ? 'active': '' ?>"
                               href="<?= $escaper->escapeUrl($category->getUrl()) ?>">
                                <?= $escaper->escapeHtml($category->getName()) ?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </div>
            <?php endif; 
			endif;
			?>
        </ul>
        <?php if(!empty($hiddenList)):
		if (count($hiddenList)): ?>
            <a class="faceted-navigation-max-items-toggle"
               href="#"
               data-mage-init='{"toggleAdvanced": {"selectorsToggleClass": "active",
               "baseToggleClass": "expanded", "toggleContainers": ".toggle-container", "newLabel": "<?= $escaper->escapeHtml(__('Show less')) ?>"}}'
               class="action">
                <?= $escaper->escapeHtml(__('Show all subcategories')) ?>
            </a>
        <?php endif; 
		endif;
		?>
    </div>
</div>
<?php endif; ?>

<?= $block->getChildHtml() ?>
