<?php
/**
 * Copyright (c) On Tap Networks Limited.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<form class="form password forget"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
        <div class="field email required">
            <div class="control">
                <input type="email" name="email" placeholder="<?= $escaper->escapeHtmlAttr(__('Email')) ?>" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Request Reset Password Link')) ?></span></button>
        </div>
    </div>
</form>
