<?php
/*
 * Copyright (c) On Tap Networks Limited.
 */
/** @var \Magento\Customer\Block\Form\Login $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="block block-customer-login">
    <div class="page-title">
        <div class="login-title">
            <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $escaper->escapeHtml(__('Login')) ?></strong>
        </div>
        <div>
            <?= $block->getChildHtml('form_customer_new') ?>
        </div>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $escaper->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="">
                <div class="field email required">
                    <div class="control">
                        <input name="login[username]" placeholder="<?= $escaper->escapeHtmlAttr(__('Email')) ?>" value="<?= $escaper->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <div class="control">
                        <input name="login[password]" placeholder="<?= $escaper->escapeHtmlAttr(__('Password')) ?>" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $escaper->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $escaper->escapeHtml(__('Sign In')) ?></span></button></div>
                </div>
                <div>
                    <?= $block->getChildHtml('customer_login_agreement') ?>
                </div>
            </fieldset>
            <div class="remind">
                <a class="action" href="<?= $escaper->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $escaper->escapeHtml(__('Forgot Your Password?')) ?></span></a>
            </div>
        </form>        
    </div>
</div>
