<?php
/**
 * Copyright (c) On Tap Networks Limited.
 */
?>

<div class="deal-container-left">
    <!-- Subcategories -->
    <div class="faceted-navigation">
        <div class="faceted-navigation-header">
            <h1 class="faceted-navigation-current-section">
                <?= $escaper->escapeHtml(__('Software')) ?>
            </h1>
            <h5 class="faceted-navigation-category-label">
                <?= $escaper->escapeHtml(__('in Electronics deals')) ?>
            </h5>
        </div>

        <div class="faceted-navigation-list">
            <ul class="faceted-navigation-items">
                <li>
                    <a href="#"><?= $escaper->escapeHtml(__('All Electronics deals')) ?></a>
                </li>
                <li>
                    <a href="#"><?= $escaper->escapeHtml(__('Accessories')) ?></a>
                </li>
                <li>
                    <a href="#"><?= $escaper->escapeHtml(__('Audio & HiFi')) ?></a>
                </li>
                <li>
                    <a href="#"><?= $escaper->escapeHtml(__('Camera & Photo')) ?></a>
                </li>
                <li>
                    <a href="#"><?= $escaper->escapeHtml(__('Computing')) ?></a>
                </li>
                <li>
                    <a href="#"><?= $escaper->escapeHtml(__('Gaming')) ?></a>
                </li>
                <li>
                    <a href="#"><?= $escaper->escapeHtml(__('Headphones')) ?></a>
                </li>
                <li>
                    <a href="#"><?= $escaper->escapeHtml(__('Home Cinema TV Video')) ?></a>
                </li>
                <li>
                    <a href="#"><?= $escaper->escapeHtml(__('Mobile Phones')) ?></a>
                </li>
                <li>
                    <a href="#"><?= $escaper->escapeHtml(__('Phone Accessories')) ?></a>
                </li>
                <li>
                    <a href="#"><?= $escaper->escapeHtml(__('RC Toys')) ?></a>
                </li>
                <li>
                    <a class="active" href="#"><?= $escaper->escapeHtml(__('Software')) ?></a>
                </li>
            </ul>
            <a class="faceted-navigation-max-items-toggle" href="#">
                <?= $escaper->escapeHtml(__('Show all subcategories')) ?>
            </a>
        </div>
    </div>

    <div class="deals-side-container">
        <div class="deals-item deals-side-deal">
            <div class="deal deal-summary">
                <!-- Product Header section -->
                <div class="deal-header">
                    <h2><?php echo __('Emma Essential Foam Mattress - 5 Sizes!') ?></h2>
                </div>

                <!-- Product Carousel section -->
                <div class="deal-imagery">
                    <a href="#" class="product-image">               
                        <img src="<?php echo $this->getViewFileUrl('images/634198.jpg'); ?>" alt="Product image" width="777" height="520"/>
                    </a>
                    
                    <div class="deal-summary-main-price-splat">
                        <div class="deal-main-price-splat deal-main-price-splat-is-state-compact">
                            <div class="deal-main-price-splat-flex-wrapper">
                                <div class="deal-main-price-splat-label"><?php echo __('Save up to'); ?></div>
                                <div class="deal-main-price-splat-new-price deal-main-price-splat-new-price-has-currency">
                                    <span class="deal-main-price-splat-currency-main"><?php echo __('56%'); ?></span>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="deal-summary-merchant-seal">
                        <div class="deal-merchant-seal">
                            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/4024922-logo.png'); ?>" alt="Emma"/>
                        </div>
                    </div>

                    <div class="overlay-overlays">
                        <div class="image-overlay-left">
                        </div>

                        <div class="image-overlay-right">
                            <img src="<?php echo $this->getViewFileUrl('images/price-drop.png'); ?>" alt="Price Drop" width="338" height="63"/>
                            <img src="<?php echo $this->getViewFileUrl('images/Eligible-for-Paypal-Credit.png'); ?>" alt="Eligible-for-Paypal-Credit" width="674" height="208"/>
                        </div>
                    </div>
                </div>

                <!-- Product Status bar section -->
                <div class="deal-lead-status-bar deal-status-bar-is-hiding-merchant">
                    <div class="deal-status-bar-wrapper">
                        <div class="deal-status-bar-item-merchant">
                            <img src="<?php echo $this->getViewFileUrl('images/3973197-logo.png'); ?>" alt="" width="161" height="73"/>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-stats 66">
                            <div class="deal-status-bar-label"><?php echo __('Bought') ?></div>
                            <div class="deal-status-bar-value"><?php echo __('6282') ?></div>
                        </div>
                        
                        <div class="deal-status-bar-item deal-status-bar-item-stats 99">
                            
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-countdown">
                            <div class="deal-status-bar__countdown"></div>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-buttons">
                            <a class="secondary tocart" href="#">
                                <span><?= __('View!') ?></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="deals-side-container">
        <div class="deals-item deals-side-deal">
            <div class="deal deal-summary">
                <!-- Product Header section -->
                <div class="deal-header">
                    <h2><?php echo __('Extra Thick Hooded Snuggle Blanket - Red, Blue, Pink or Grey') ?></h2>
                </div>

                <!-- Product Carousel section -->
                <div class="deal-imagery">
                    <a href="#" class="product-image">               
                        <img src="<?php echo $this->getViewFileUrl('images/634198.jpg'); ?>" alt="Product image" width="777" height="520"/>
                    </a>
                    
                    <div class="deal-summary-main-price-splat">
                        <div class="deal-main-price-splat deal-main-price-splat-is-state-compact">
                            <div class="deal-main-price-splat-flex-wrapper">
                                <div class="deal-main-price-splat-label"><?php echo __('From'); ?></div>
                                <div class="deal-main-price-splat-new-price deal-main-price-splat-new-price-has-currency">
                                    <span class="deal-main-price-splat-currency-main"><?php echo __('85%'); ?></span>
                                </div>
                                <span class="deal-main-price-splat-old-price strikethrough">
                                    <span><?php echo __('£400'); ?></span>
                                </span>
                            </div>

                        </div>
                    </div>

                    <div class="deal-summary-merchant-seal">
                        <div class="deal-merchant-seal">
                            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/4024922-logo.png'); ?>" alt="Emma"/>
                        </div>
                    </div>

                    <div class="overlay-overlays">
                        <div class="image-overlay-left">
                        </div>

                        <div class="image-overlay-right">
                            <img src="<?php echo $this->getViewFileUrl('images/price-drop.png'); ?>" alt="Price Drop" width="338" height="63"/>
                            <img src="<?php echo $this->getViewFileUrl('images/4XmasOFDAYS2020.png'); ?>" alt="" width="674" height="402"/>
                        </div>
                    </div>
                </div>

                <!-- Product Status bar section -->
                <div class="deal-lead-status-bar deal-status-bar-is-hiding-merchant">
                    <div class="deal-status-bar-wrapper">
                        <div class="deal-status-bar-item-merchant">
                            <img src="<?php echo $this->getViewFileUrl('images/3973197-logo.png'); ?>" alt="" width="161" height="73"/>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-stats">
                            <div class="deal-status-bar-label"><?php echo __('Bought') ?></div>
                            <div class="deal-status-bar-value"><?php echo __('3246') ?></div>
                        </div>
                        
                        <div class="deal-status-bar-item deal-status-bar-item-stats">
                            <div class="deal-status-bar-label"><?php echo __('Save up to') ?></div>
                            <div class="deal-status-bar-value"><?php echo __('63%') ?></div>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-countdown">
                            <div class="deal-status-bar__countdown"></div>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-buttons">
                            <a class="secondary tocart" href="#">
                                <span><?= __('View!') ?></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

