<?php
/**
 * Copyright (c) On Tap Networks Limited.
 */
?>

<div class="deal-container-main">

    <!-- Main deal -->
    <div class="deals-item deals-primary-deal homepage">
        <!-- Product Header section -->
        <div class="deal-header">
            <h1><?php echo __('Personalised Photo Blanket – Fleece or Mink Touch in 3 Sizes') ?></h1>
            <h3><?php echo __('£8 instead of £47.94 for a medium personalised photo throw, £15 for a large photo throw or £30 for an extra-large throw from Printerpix! - save up to 83%') ?></h3>
        </div>

        <!-- Product Carousel section -->
        <div class="deal-lead-image-wrapper">
            <div class="product-image">               
                <img src="<?php echo $this->getViewFileUrl('images/648066.jpg'); ?>" alt="Product image"/>
            </div>

            <div class="prev-next-button previous"></div>
            <div class="prev-next-button next"></div>

            <div class="deal-product-image-thumb slider-thumbnails-has-video">
                <div class="slider-item active">
                    <img src="<?php echo $this->getViewFileUrl('images/648066-thumb.jpg'); ?>" alt="Product image"/>
                </div>
                <div class="slider-item">
                    <img src="<?php echo $this->getViewFileUrl('images/648066-thumb.jpg'); ?>" alt="Product image"/>
                </div>
                <div class="slider-item">
                    <img src="<?php echo $this->getViewFileUrl('images/648066-thumb.jpg'); ?>" alt="Product image"/>
                </div>
                <div class="slider-item">
                    <img src="<?php echo $this->getViewFileUrl('images/648066-thumb.jpg'); ?>" alt="Product image"/>
                </div>
            </div>

            <div class="deal-lead-main-price-splat">
                <div class="deal-main-price-splat">
                    <div class="deal-main-price-splat-flex-wrapper">
                        <div class="deal-main-price-splat-label"><?php echo __('From'); ?></div>
                        <div class="deal-main-price-splat-new-price deal-main-price-splat-new-price-has-currency">
                            <span class="deal-main-price-splat-currency-main"><?php echo __('£8'); ?></span>
                        </div>
                        <span class="deal-main-price-splat-old-price strikethrough">
                            <a href="#" target="_blank" class="deal-main-price-splat-price-link">
                                <span ng-if="$ctrl.cmpOldPrice.pounds"><?php echo __('£47'); ?></span>
                                <span ng-if="$ctrl.cmpOldPrice.pence"><?php echo __('.94'); ?></span>
                            </a>
                        </span>
                    </div>

                </div>
            </div>
        </div>

        <!-- Product Status bar section -->
        <div class="deal-lead-status-bar deal-status-bar-is-hiding-merchant deal-status-bar-is-video">
            <div class="deal-status-bar-wrapper">
                <div class="deal-status-bar-item-merchant">
                    
                </div>

                <div class="deal-status-bar-item deal-status-bar-item-stats">
                    <div class="deal-status-bar-label"><?php echo __('Bought') ?></div>
                    <div class="deal-status-bar-value"><?php echo __('17190') ?></div>
                </div>
                
                <div class="deal-status-bar-item deal-status-bar-item-stats">
                    <div class="deal-status-bar-label"><?php echo __('Save up to') ?></div>
                    <div class="deal-status-bar-value"><?php echo __('83%') ?></div>
                </div>

                <div class="deal-status-bar-item deal-status-bar-item-countdown">
                    <div class="deal-status-bar__countdown"></div>
                </div>

                <div class="deal-status-bar-item deal-status-bar-item-buttons">
                    <div class="deal-status-bar-buttons">
                        <a class="secondary tocart button-is-state-compact button-is-dropdown-deal" href="#">
                            <span><?php echo __('choose your options') ?></span>
                        </a>
                        <a href="#" class="button-is-quaternary button-is-full-width">
                            <?php echo __('Give As A Gift') ?>
                        </a>
                    </div>                    
                </div>
            </div>
        </div>

        <!-- Content -->
        <div class="cue-message-container">
            <p class="cue-message">
                <img src="<?php echo $this->getViewFileUrl('images/exclamation-circle.png'); ?>" alt="cue-message-icon"/>
                <?php echo __('IN HIGH DEMAND!') ?>
            </p>
            <p class="cue-message cue-message-bought">
                <img src="<?php echo $this->getViewFileUrl('images/users.png'); ?>" alt="cue-message-icon" width="20" height="11"/>
                <?php echo __('61 others bought this deal in the last 24 hours!') ?>
            </p>

        </div>

        <div class="deal deal-details-wide">
            <div class="deal-details-wide-container">
                <div class="deal-details-wide-logo">
                    <a href="#">
                        <img src="<?php echo $this->getViewFileUrl('images/4028390-logo.png'); ?>" alt=""/>
                    </a>
                </div>
                <div class="deal-social-shares">
                    <img src="<?php echo $this->getViewFileUrl('images/social-share.png'); ?>" alt=""/>
                </div>
            </div>

            <div class="deal-details-wide-container">
                <div class="deal-details-columns">
                    <h2 class="deal-details-wide-heading">Highlights</h2>
                    <div class="deal-details-wide-bullet-list">
                        <ul class="deal-bullet-list">
                            <li><b>Photo blanket:</b> Get a personalised photo throw.</li>
                            <li><b>Personalised:</b> Upload your own image with the easy-to-use online tool.</li>
                            <li><b>Three sizes:</b> Choose between medium, large or extra-large (see full details for dimensions).</li>
                            <li><b>Two options:</b> Comes in soft mink touch or fleece options.</li>
                            <li><b>High-quality:</b> Printed using colourful, high-definition ink.</li>
                            <li><b>Machine washable:</b> Wash on low heat.</li>                        
                        </ul>
                    </div>
                </div>
                <div class="deal-details-columns">
                    <h2 class="deal-details-wide-heading">The Fine Print</h2>
                    <div class="deal-details-wide-bullet-list">
                        <ul class="deal-bullet-list">
                            <li>May buy multiples.</li>
                            <li>Voucher valid 7th Dec 2020.</li>
                            <li>Delivery costs an additional £6.99 per voucher.</li>
                            <li>
                            Delivery excludes selected postcodes in
                                <a href="#" target="_blank"> Isle of Man</a>,
                                <a href="#" target="_blank"> Channel Islands</a>,
                                <a href="#" target="_blank"> Scottish Islands</a>, 
                                <a href="#" target="_blank"> Scottish Highlands</a> and 
                                <a href="#" target="_blank"> Northern Ireland </a>.
                            </li>
                            <li>Please allow up to 15 working days for delivery after redeeming. </li>
                            <li>Marketing credits cannot be applied to this deal.</li>
                            <li>Subject to availability. </li>   
                        </ul>
                    </div>
                </div>
            </div>

            <div class="deal-details-wide-container one-column">
                <h2 class="deal-details-wide-heading">Full Details</h2>
                <div class="deal-rich-text">
                    <div class="deal-rich-text">
                        <p>Let’s make this <i>personal</i>…</p>
                        <p>  We’re offering you a <b>medium personalised photo blanket</b> for <b>£8</b>, a <b>large blanket</b> for <b>£15</b> or an <b>extra-large blanket</b> for just <b>£30</b>.</p>
                        <h3>Sizes:</h3>
                        <ul>
                            <li><b>Medium:</b> (L) 101cm x (W) 76cm</li>
                            <li><b>Large:</b> (L) 152cm x (W) 127cm</li>
                            <li><b>Extra-large:</b> (L) 203cm x (W) 152cm</li></ul>
                            <h3>Check out our other related deals:</h3>
                            <ul><li><a href="#" target="_blank">Personalised iterms </a></li>
                            <li><a href="#" target="_blank">Personalised pillowcases </a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="deal-details-wide-container one-column">
                <h2 class="deal-details-wide-heading">Location</h2>
                <p class="deal-redeemable-locations-text">
                    <a target="_blank" class="deal-redeemable-locations-link" href="#">Click here</a> for a full list of redeemable locations
                </p>
            </div>

            <div class="deal-details-wide-container one-column">
                <h2 class="deal-details-wide-heading">How to Redeem</h2>
                <div class="deal-details-wide-bullet-list">
                    <ul class="deal-bullet-list">
                        <li>When you’ve bought we’ll send you your unique code.</li>
                        <li>Head to Printerpix’s site using the link we send you.</li>
                        <li>Add the product to your cart.</li>
                        <li>Enter your code when prompted.</li>
                    </ul>
                </div>
                <p class="deal-details-wide-redeem-text">
                    Once purchased, you can redeem this Wowcher towards another Wowcher or claim a Wowcher Wallet Credit.
                    <a class="deal-details-narrow-redeem-link" href="#" target="_blank">Click here for more info</a>
                </p>
            </div>

            <div class="deal-details-wide-container one-column">
                <em>This deal is brought to you by Print Express t/a Printerpix
                    <span>, VAT number: GB226235189</span>.
                </em>
            </div>

            <div class="deal-details-wide-container one-column">
                <img class="deal-details-wide-small-image" src="https://resources.wowcher.co.uk/images/paypal-credit-logo.svg" alt="PayPal Credit Logo">
                <span>Spend £99 or more to enjoy 0% interest for 4 months.</span>
                <a class="deal-details-narrow-redeem-link" target="_blank" href="https://www.paypal.com/uk/webapps/mpp/paypal-virtual-credit/faq">Click for details.</a>
            </div>

            <div class="deal-details-wide-container one-column">
                <div class="deal-details-wide-reassuance">
                    <div class="social-reassurance-container">
                        <p class="message">
                            No quibble 14 day refund guarantee on unredeemed vouchers
                        </p>
                        <p class="message">
                            Change your mind? You can redeem this towards any other deal on site
                        </p>
                    </div>
                </div>
                <div class="deal-details-wide-buy-button">
                    <a class="button secondary button-is-full-width button-is-state-compact button-is-dropdown-deal" href="#">
                        <span><?php echo __('choose your options') ?></span>
                    </a>
                </div>
            </div>

        </div>
    </div>


    <!-- Secondary deal -->
    <div class="deals-item deals-secondary-deal">
        <!-- Product Header section -->
        <div class="deal-header">
            <h1><?php echo __('Emma Original Renewed Mattress - 5 Sizes!') ?></h1>
            <h3><?php echo __('From £119 instead of £319 for a renewed Emma Original mattress - get the UK\'s number one most awarded mattress* from Emma and save up to 63%') ?></h3>
        </div>

        <!-- Product Carousel section -->
        <div class="deal-lead-image-wrapper">
            <div class="product-image">               
                <img src="<?php echo $this->getViewFileUrl('images/633404.jpg'); ?>" alt="Product image"/>
            </div>

            <div class="prev-next-button previous"></div>
            <div class="prev-next-button next"></div>

            <div class="deal-product-image-thumb">
                <div class="slider-item active">
                    <img src="<?php echo $this->getViewFileUrl('images/633404-thumb.jpg'); ?>" alt="Product image"/>
                </div>
                <div class="slider-item">
                    <img src="<?php echo $this->getViewFileUrl('images/633404-thumb.jpg'); ?>" alt="Product image"/>
                </div>
                <div class="slider-item">
                    <img src="<?php echo $this->getViewFileUrl('images/633404-thumb.jpg'); ?>" alt="Product image"/>
                </div>
                <div class="slider-item">
                    <img src="<?php echo $this->getViewFileUrl('images/633404-thumb.jpg'); ?>" alt="Product image"/>
                </div>
            </div>
            
            <div class="deal-lead-club-points">
                <div class="deal-club-points-text">
                    <?php echo __('Collect 11,900 Club Wowcher points') ?>
                </div>
            </div>           
        </div>

        <!-- Product Status bar section -->
        <div class="deal-lead-status-bar">
            <div class="deal-status-bar-wrapper">
                <div class="deal-status-bar-item-merchant">
                    <img src="<?php echo $this->getViewFileUrl('images/4027810-logo.png'); ?>" alt=""/>
                </div>

                <div class="deal-status-bar-item deal-status-bar-item-stats">
                    <div class="deal-status-bar-label"><?php echo __('Bought') ?></div>
                    <div class="deal-status-bar-value"><?php echo __('3246') ?></div>
                </div>
                
                <div class="deal-status-bar-item deal-status-bar-item-stats">
                    <div class="deal-status-bar-label"><?php echo __('Save up to') ?></div>
                    <div class="deal-status-bar-value"><?php echo __('63%') ?></div>
                </div>

                <div class="deal-status-bar-item deal-status-bar-item-countdown">
                    <div class="deal-status-bar__countdown"></div>
                </div>

                <div class="deal-status-bar-item deal-status-bar-item-buttons">
                    <a class="secondary tocart" href="#">
                        <span><?= __('View!') ?></span>
                    </a>
                </div>
            </div>
        </div>
    </div>

    
    <div class="deals-item deals-secondary-deal">
        <!-- Product Header section -->
        <div class="deal-header">
            <h1><?php echo __('Extra Thick Hooded Snuggle Blanket - Red, Blue, Pink or Grey') ?></h1>
            <h3><?php echo __('£13 instead of £49.99 for a hooded fleece blanket with sleeves from Magic Trend - save 74%') ?></h3>
        </div>

        <!-- Product Carousel section -->
        <div class="deal-lead-image-wrapper">
            <div class="product-image">               
                <img src="<?php echo $this->getViewFileUrl('images/633404.jpg'); ?>" alt="Product image"/>
            </div>

            <div class="prev-next-button previous"></div>
            <div class="prev-next-button next"></div>

            <div class="deal-product-image-thumb">
                <div class="slider-item active">
                    <img src="<?php echo $this->getViewFileUrl('images/633404-thumb.jpg'); ?>" alt="Product image"/>
                </div>
                <div class="slider-item">
                    <img src="<?php echo $this->getViewFileUrl('images/633404-thumb.jpg'); ?>" alt="Product image"/>
                </div>
                <div class="slider-item">
                    <img src="<?php echo $this->getViewFileUrl('images/633404-thumb.jpg'); ?>" alt="Product image"/>
                </div>
                <div class="slider-item">
                    <img src="<?php echo $this->getViewFileUrl('images/633404-thumb.jpg'); ?>" alt="Product image"/>
                </div>
            </div>
            
            <div class="deal-lead-club-points">
                <div class="deal-club-points-text">
                    <?php echo __('Collect 1,499 Club Wowcher points') ?>
                </div>
            </div>

            <div class="overlay-overlays">
                <div class="image-overlay-left">
                </div>

                <div class="image-overlay-right">
                    <img src="<?php echo $this->getViewFileUrl('images/price-drop.png'); ?>" alt="Price Drop" width="338" height="63"/>
                    <img src="<?php echo $this->getViewFileUrl('images/4XmasOFDAYS2020.png'); ?>" alt="Days off" width="674" height="402"/>                    
                </div>
            </div>
        </div>

        <!-- Product Status bar section -->
        <div class="deal-lead-status-bar">
            <div class="deal-status-bar-wrapper">
                <div class="deal-status-bar-item-merchant">
                    <img src="<?php echo $this->getViewFileUrl('images/4027810-logo.png'); ?>" alt=""/>
                </div>

                <div class="deal-status-bar-item deal-status-bar-item-stats">
                    <div class="deal-status-bar-label"><?php echo __('Bought') ?></div>
                    <div class="deal-status-bar-value"><?php echo __('17939') ?></div>
                </div>
                
                <div class="deal-status-bar-item deal-status-bar-item-stats">
                    <div class="deal-status-bar-label"><?php echo __('Save') ?></div>
                    <div class="deal-status-bar-value"><?php echo __('74%') ?></div>
                </div>

                <div class="deal-status-bar-item deal-status-bar-item-countdown">
                    <div class="deal-status-bar__countdown"></div>
                </div>

                <div class="deal-status-bar-item deal-status-bar-item-buttons">
                    <a class="secondary tocart" href="#">
                        <span><?= __('View!') ?></span>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="deals-item deals-secondary-deal">
        <!-- Product Header section -->
        <div class="deal-header">
            <h1><?php echo __('Grey Fabric Divan Bed Set with Headboard & Memory Foam Mattress') ?></h1>
            <h3><?php echo __('From £79 instead of £399 for a grey fabric divan bed set with a headboard and memory mattress from Dining Tables - save up to 80%') ?></h3>
        </div>

        <!-- Product Carousel section -->
        <div class="deal-lead-image-wrapper">
            <div class="product-image">               
                <img src="<?php echo $this->getViewFileUrl('images/633404.jpg'); ?>" alt="Product image"/>
            </div>

            <div class="deal-product-image-thumb">
                <div class="slider-item active">
                    <img src="<?php echo $this->getViewFileUrl('images/633404-thumb.jpg'); ?>" alt="Product image"/>
                </div>
                <div class="slider-item">
                    <img src="<?php echo $this->getViewFileUrl('images/633404-thumb.jpg'); ?>" alt="Product image"/>
                </div>
                <div class="slider-item">
                    <img src="<?php echo $this->getViewFileUrl('images/633404-thumb.jpg'); ?>" alt="Product image"/>
                </div>
                <div class="slider-item">
                    <img src="<?php echo $this->getViewFileUrl('images/633404-thumb.jpg'); ?>" alt="Product image"/>
                </div>
            </div>
            
            <div class="deal-lead-club-points">
                <div class="deal-club-points-text">
                    <?php echo __('Collect 1,499 Club Wowcher points') ?>
                </div>
            </div>

            <div class="overlay-overlays">
                <div class="image-overlay-left">
                </div>

                <div class="image-overlay-right">
                    <img src="<?php echo $this->getViewFileUrl('images/Eligible-for-Paypal-Credit.png'); ?>" alt="Eligible-for-Paypal-Credit" width="674" height="208"/>
                </div>
            </div>
        </div>

        <!-- Product Status bar section -->
        <div class="deal-lead-status-bar">
            <div class="deal-status-bar-wrapper">
                <div class="deal-status-bar-item-merchant">
                    <img src="<?php echo $this->getViewFileUrl('images/4027810-logo.png'); ?>" alt=""/>
                </div>

                <div class="deal-status-bar-item deal-status-bar-item-stats">
                    <div class="deal-status-bar-label"><?php echo __('Bought') ?></div>
                    <div class="deal-status-bar-value"><?php echo __('17939') ?></div>
                </div>
                
                <div class="deal-status-bar-item deal-status-bar-item-stats">
                    <div class="deal-status-bar-label"><?php echo __('Save') ?></div>
                    <div class="deal-status-bar-value"><?php echo __('74%') ?></div>
                </div>

                <div class="deal-status-bar-item deal-status-bar-item-countdown">
                    <div class="deal-status-bar__countdown"></div>
                </div>

                <div class="deal-status-bar-item deal-status-bar-item-buttons">
                    <a class="secondary tocart" href="#">
                        <span><?= __('View!') ?></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
