<?php
/**
 * Copyright (c) On Tap Networks Limited.
 */
?>
<!-- Desktop view -->
<div class="deal-container-bottom">
    <div class="deals-secondary-container">
        <div class="deals-item deals-secondary-deal">
            <div class="deal deal-summary">
                <!-- Product Header section -->
                <div class="deal-header">
                    <h2><?php echo __('Memory Foam Quilted Sprung Mattress - 7 or 10"') ?></h2>
                </div>

                <!-- Product Carousel section -->
                <div class="deal-imagery">
                    <a href="#" class="product-image">               
                        <img src="<?php echo $this->getViewFileUrl('images/634198.jpg'); ?>" alt="Product image" width="777" height="520"/>
                    </a>
                    
                    <div class="deal-summary-main-price-splat">
                        <div class="deal-main-price-splat deal-main-price-splat-is-state-compact">
                            <div class="deal-main-price-splat-flex-wrapper">
                                <div class="deal-main-price-splat-label"><?php echo __('Save up to'); ?></div>
                                <div class="deal-main-price-splat-new-price deal-main-price-splat-new-price-has-currency">
                                    <span class="deal-main-price-splat-currency-main"><?php echo __('85%'); ?></span>
                                </div>
                                <span class="deal-main-price-splat-old-price strikethrough">
                                    <span><?php echo __('£400'); ?></span>
                                </span>
                            </div>

                        </div>
                    </div>
                </div>

                <!-- Product Status bar section -->
                <div class="deal-lead-status-bar">
                    <div class="deal-status-bar-wrapper">
                        <div class="deal-status-bar-item-merchant">
                            <img src="<?php echo $this->getViewFileUrl('images/3973197-logo.png'); ?>" alt="" width="161" height="73"/>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-stats">
                            <div class="deal-status-bar-label"><?php echo __('Bought') ?></div>
                            <div class="deal-status-bar-value"><?php echo __('3246') ?></div>
                        </div>
                        
                        <div class="deal-status-bar-item deal-status-bar-item-stats">
                            <div class="deal-status-bar-label"><?php echo __('Save up to') ?></div>
                            <div class="deal-status-bar-value"><?php echo __('63%') ?></div>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-countdown">
                            <div class="deal-status-bar__countdown"></div>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-buttons">
                            <a class="secondary tocart" href="#">
                                <span><?= __('View!') ?></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="deals-secondary-container">
        <div class="deals-item deals-secondary-deal">
            <div class="deal deal-summary">
                <!-- Product Header section -->
                <div class="deal-header">
                    <h2><?php echo __('Crushed Velvet Divan Bed W/ Mattress - 6 Sizes & Drawer Options') ?></h2>
                </div>

                <!-- Product Carousel section -->
                <div class="deal-imagery">
                    <a href="#" class="product-image">               
                        <img src="<?php echo $this->getViewFileUrl('images/634198.jpg'); ?>" alt="Product image" width="777" height="520"/>
                    </a>
                    
                    <div class="deal-summary-main-price-splat">
                        <div class="deal-main-price-splat deal-main-price-splat-is-state-compact">
                            <div class="deal-main-price-splat-flex-wrapper">
                                <div class="deal-main-price-splat-label"><?php echo __('Save up to'); ?></div>
                                <div class="deal-main-price-splat-new-price deal-main-price-splat-new-price-has-currency">
                                    <span class="deal-main-price-splat-currency-main"><?php echo __('85%'); ?></span>
                                </div>
                                <span class="deal-main-price-splat-old-price strikethrough">
                                    <span><?php echo __('£400'); ?></span>
                                </span>
                            </div>

                        </div>
                    </div>
                    <div class="overlay-overlays">
                        <div class="image-overlay-left">
                        </div>

                        <div class="image-overlay-right">
                            <img src="<?php echo $this->getViewFileUrl('images/Eligible-for-Paypal-Credit.png'); ?>" alt="Eligible-for-Paypal-Credit" width="674" height="208"/>
                            <img src="<?php echo $this->getViewFileUrl('images/wow-SPEEDY-DELIVERY.png'); ?>" alt="wow Speedy Delivery"/>
                        </div>
                    </div>
                </div>

                <!-- Product Status bar section -->
                <div class="deal-lead-status-bar">
                    <div class="deal-status-bar-wrapper">
                        <div class="deal-status-bar-item-merchant">
                            <img src="<?php echo $this->getViewFileUrl('images/3973197-logo.png'); ?>" alt="" width="161" height="73"/>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-stats">
                            <div class="deal-status-bar-label"><?php echo __('Bought') ?></div>
                            <div class="deal-status-bar-value"><?php echo __('3246') ?></div>
                        </div>
                        
                        <div class="deal-status-bar-item deal-status-bar-item-stats">
                            <div class="deal-status-bar-label"><?php echo __('Save up to') ?></div>
                            <div class="deal-status-bar-value"><?php echo __('63%') ?></div>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-countdown">
                            <div class="deal-status-bar__countdown"></div>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-buttons">
                            <a class="secondary tocart" href="#">
                                <span><?= __('View!') ?></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="deals-secondary-container">
        <div class="deals-item deals-secondary-deal">
            <div class="deal deal-summary">
                <!-- Product Header section -->
                <div class="deal-header">
                    <h2><?php echo __('Gas Lift Ottoman Storage Bed Frame with Mattress Option - 4 Sizes') ?></h2>
                </div>

                <!-- Product Carousel section -->
                <div class="deal-imagery">
                    <a href="#" class="product-image">               
                        <img src="<?php echo $this->getViewFileUrl('images/634198.jpg'); ?>" alt="Product image" width="777" height="520"/>
                    </a>
                    
                    <div class="deal-summary-main-price-splat">
                        <div class="deal-main-price-splat deal-main-price-splat-is-state-compact">
                            <div class="deal-main-price-splat-flex-wrapper">
                                <div class="deal-main-price-splat-label"><?php echo __('Save up to'); ?></div>
                                <div class="deal-main-price-splat-new-price deal-main-price-splat-new-price-has-currency">
                                    <span class="deal-main-price-splat-currency-main"><?php echo __('85%'); ?></span>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="overlay-overlays">
                        <div class="image-overlay-left">
                            <img src="<?php echo $this->getViewFileUrl('images/Extended-Delivery-Fine-Print.png'); ?>" alt="Extended-Delivery-Fine-Print"/>
                        </div>

                        <div class="image-overlay-right">
                            <img src="<?php echo $this->getViewFileUrl('images/Eligible-for-Paypal-Credit.png'); ?>" alt="Eligible-for-Paypal-Credit" width="674" height="208"/>
                        </div>
                    </div>
                </div>

                <!-- Product Status bar section -->
                <div class="deal-lead-status-bar">
                    <div class="deal-status-bar-wrapper">
                        <div class="deal-status-bar-item-merchant">
                            <img src="<?php echo $this->getViewFileUrl('images/3973197-logo.png'); ?>" alt="" width="161" height="73"/>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-stats">
                            <div class="deal-status-bar-label"><?php echo __('Bought') ?></div>
                            <div class="deal-status-bar-value"><?php echo __('3246') ?></div>
                        </div>
                        
                        <div class="deal-status-bar-item deal-status-bar-item-stats">
                            <div class="deal-status-bar-label"><?php echo __('Save up to') ?></div>
                            <div class="deal-status-bar-value"><?php echo __('63%') ?></div>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-countdown">
                            <div class="deal-status-bar__countdown"></div>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-buttons">
                            <a class="secondary tocart" href="#">
                                <span><?= __('View!') ?></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="deals-secondary-container">
        <div class="deals-item deals-secondary-deal">
            <div class="deal deal-summary">
                <!-- Product Header section -->
                <div class="deal-header">
                    <h2><?php echo __('Wooden Ottoman Bed - 3 Mattress Options & 3 Sizes!') ?></h2>
                </div>

                <!-- Product Carousel section -->
                <div class="deal-imagery">
                    <a href="#" class="product-image">               
                        <img src="<?php echo $this->getViewFileUrl('images/634198.jpg'); ?>" alt="Product image" width="777" height="520"/>
                    </a>
                    
                    <div class="deal-summary-main-price-splat">
                        <div class="deal-main-price-splat deal-main-price-splat-is-state-compact">
                            <div class="deal-main-price-splat-flex-wrapper">
                                <div class="deal-main-price-splat-label"><?php echo __('Save up to'); ?></div>
                                <div class="deal-main-price-splat-new-price deal-main-price-splat-new-price-has-currency">
                                    <span class="deal-main-price-splat-currency-main"><?php echo __('85%'); ?></span>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="overlay-overlays">
                        <div class="image-overlay-left">
                            <img src="<?php echo $this->getViewFileUrl('images/Extended-Delivery-Fine-Print.png'); ?>" alt="Extended-Delivery-Fine-Print"/>
                        </div>

                        <div class="image-overlay-right">
                            <img src="<?php echo $this->getViewFileUrl('images/Eligible-for-Paypal-Credit.png'); ?>" alt="Eligible-for-Paypal-Credit" width="674" height="208"/>
                        </div>
                    </div>
                </div>

                <!-- Product Status bar section -->
                <div class="deal-lead-status-bar">
                    <div class="deal-status-bar-wrapper">
                        <div class="deal-status-bar-item-merchant">
                            <img src="<?php echo $this->getViewFileUrl('images/3973197-logo.png'); ?>" alt="" width="161" height="73"/>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-stats">
                            <div class="deal-status-bar-label"><?php echo __('Bought') ?></div>
                            <div class="deal-status-bar-value"><?php echo __('3246') ?></div>
                        </div>
                        
                        <div class="deal-status-bar-item deal-status-bar-item-stats">
                            <div class="deal-status-bar-label"><?php echo __('Save up to') ?></div>
                            <div class="deal-status-bar-value"><?php echo __('63%') ?></div>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-countdown">
                            <div class="deal-status-bar__countdown"></div>
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-buttons">
                            <a class="secondary tocart" href="#">
                                <span><?= __('View!') ?></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <button class="button secondary load-more">
        <?php echo __('Load more') ?>
    </button>   
</div>
