<?php

// @codingStandardsIgnoreFile

/* @var $block \Cordial\Sync\Block\Html\Loader */

if ($block->isEnable()): 
  $events = $block->getJsEvent();
?>

<?php if ($block->getJsV2Enabled()): ?>
<div data-bind="scope: 'cordial'">
    <div data-bind="html: events().data"><?php echo $events; ?></div>
</div>
<?php else: ?>
<div data-bind="scope: 'cordial'">
    <div data-bind="html: events().data"><?php echo $events; ?></div>
</div>
<?php endif; ?>

<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "cordial": {
                            "component": "Cordial_Sync/js/cordial-events"
                        }
                    }
                }
            }
        }
</script>
<?php
endif;
