<?php

/** @var \Scommerce\GlobalSiteTag\Helper\Data $helper */
$helper = $this->getHelper();

if (!$helper->isEnabled()) return;
?>

<?php if ($helper->getOptimizeId() && $helper->isOptimizeEnabled()): ?>
    <!-- Scommerce Mage Anti-flicker snippet -->
    <style>.async-hide { opacity: 0 !important} </style>
    <script>(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;
			h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};
			(a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;
		})(window,document.documentElement,'async-hide','dataLayer',4000,
			{'<?= $helper->getOptimizeId(); ?>':true});
    </script>
<?php endif; ?>
