<?php
/*
 * Copyright (c) On Tap Networks Limited.
 */

/** @var \Magento\Catalog\Block\Product\View $block */
/** @var \Magento\Framework\Escaper $escaper */
$product = $block->getProduct();
/** @var \OnTap\Deal\ViewModel\SocialCue\TotalRemaining $totalRemainingCue */
$totalRemainingCue = $block->getTotalRemaining();
$stockMessage = $totalRemainingCue->getMessage($product);
$sku = $product->getSku();
$socialCuemsg = $totalRemainingCue->getsocialCuedeal($sku);
?>

<?php if ($totalRemainingCue->canShow($product) && $stockMessage): ?>
    <p class="cue-message">
        <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/exclamation-circle.png')) ?>"
             alt="<?= $escaper->escapeHtml('cue-message-icon') ?>"
             width="16"
             height="16"/>
        <?= $escaper->escapeHtml($stockMessage) ?>
        
    </p>
    
    <?php endif; ?>
    <?php if ($socialCuemsg): ?>
<p class="cue-message cue-message--bought" style="color: #01b901 !important;">
    <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('images/greenicon.png')) ?>"
             alt="<?= $escaper->escapeHtml('cue-message-icon') ?>"
             width="16"
             height="16"/>
    <?= $escaper->escapeHtml($socialCuemsg) ?></p>
 <?php endif; ?>
<div class="deal-details-narrow-title">
    <?= $block->getProduct()->getData('short_description') ?>
</div>
