<?php
/** @var \Magento\Catalog\Block\Product\View $block */
/** @var \Magento\Framework\Escaper $escaper */
$product = $block->getProduct();
$associatedProducts = $product->getTypeInstance()->getAssociatedProducts($product);
$child_count = count($associatedProducts);
//echo $product->getTypeId();
/** @var \OnTap\Deal\ViewModel\SocialCue\TotalBought $totalBoughtCue */
$totalBoughtCue = $block->getTotalBought();
/** @var \OnTap\Deal\ViewModel\SocialCue\SaveUpTo $saveUpToCue */
$saveUpToCue = $block->getSaveUpTo();
$pro_id = $product->getId();
?>
<div class="deal-status-bar-wrapper">
    <div class="product-name-mobile"><?= $escaper->escapeHtml($product->getName()) ?></div>
    <div class="deal-status-bar-item-merchant">
    </div>

    <?php if ($totalBoughtCue->canShow($product)): ?>
        <div class="deal-status-bar-item deal-status-bar-item-stats">
            <div class="deal-status-bar-label"><?php echo __('Bought') ?>+</div>
            <div class="deal-status-bar-value">
                <?= $escaper->escapeHtml($totalBoughtCue->getValue($product)); ?>
            </div>
        </div>
    <?php endif; ?>

    <?php if ($saveUpToCue->canShow($product)): ?>
        <div class="deal-status-bar-item deal-status-bar-item-stats">
            <div class="deal-status-bar-label"><?php echo __('Save up to') ?></div>
            <div class="deal-status-bar-value"><?= $saveUpToCue->getValue($product) ?></div>
        </div>
    <?php endif; ?>

    <div class="deal-status-bar-item deal-status-bar-item-countdown">
    <?php
                        $exipry_date = $product->getCountdownTimer();
                        if($exipry_date != ''){
                        ?>
                        <div class="deal-status-bar-label"><?php echo __('Time Remaining') ?></div>
                        <div class="deal-status-bar-value large" id="race<?php echo $pro_id; ?>"></div>
                        <?php } ?>  
    </div>
<?php if($child_count > 1){?>
    <div class="deal-status-bar-item deal-status-bar-item-buttons">
        <a class="secondary tocart" href="#product_addtocart_form">
            <span><?= __('Buy!') ?></span>
        </a>
    </div>
    <?php }else{ ?>
    <div class="deal-status-bar-item deal-status-bar-item-buttons buydirect">
        <a class="secondary tocart" href="javascript:void(0)">
            <span><?= __('Buy!') ?></span>
        </a>
    </div>
    <script>
require(['jquery'],function($){
     $(document).ready(function(){
     	$('.buydirect').click(function(){
        $('#product-addtocart-button').click();
        //$('#buydirect').hide();
    });
     });
       });
</script>

    <?php } ?>
</div>

<script>
// Set the date we're counting down to
var countdownsM = [
<?php 
$exipry_date = $product->getCountdownTimer();
$formated_date = substr($exipry_date, 0, -3);
$date_time = date('m/d/Y H:i:s', $formated_date);

if($exipry_date != ''){
?>
  {
    id: <?php echo $product->getId() ?>,
    date: new Date("<?php echo date('M j, Y H:i:s', strtotime($date_time));?>").getTime()
  },
<?php } ?>
];

// Update the count down every 1 second
var timer = setInterval(function() {
  // Get todays date and time
  var now = Date.now();

  var index = countdownsM.length - 1;

  // we have to loop backwards since we will be removing
  // countdowns when they are finished
  while(index >= 0) {
    var countdown = countdownsM[index];

    // Find the distance between now and the count down date
    var distance = countdown.date - now;

    // Time calculations for days, hours, minutes and seconds
    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);

    var timerElement = document.getElementById("race" + countdown.id);

    // If the count down is over, write some text 
    if (distance < 0) {
      var date = new Date(countdown.date);
	var next_threedate = date.setDate(date.getDate() + 3);
    var distance = next_threedate - now;
     var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    if(days == 0){
      timerElement.innerHTML =  hours + "h " + minutes + "m " + seconds + "s ";
      }
      else{
      timerElement.innerHTML =  days + "d " + hours + "h " + minutes + "m " + seconds + "s ";
      }
      // this timer is done, remove it
      //countdownsL.splice(index, 1);
    } else {
    if(days == 0){
      timerElement.innerHTML =  hours + "h " + minutes + "m " + seconds + "s ";
      }
      else{
      timerElement.innerHTML =  days + "d " + hours + "h " + minutes + "m " + seconds + "s ";
      }
      //timerElement.innerHTML =  days + "D " + hours + "H " + minutes + "M ";
    }

    index -= 1;
  }

  // if all countdowns have finished, stop timer
  if (countdownsM.length < 1) {
    clearInterval(timer);
  }
}, 1000);
</script>  
