<?php
/** @var \Freshrelevance\Digitaldatalayer\Block\DdlProduct $block */
$helper = $this->helper('Freshrelevance\Digitaldatalayer\Helper\PageType');
$values = $helper->getCurrentPage();
?>

<?php if ($values != 'cms_index_index'): ?>
    <script type="text/javascript">
        (function () {
            window.dod = (<?= $block->getTransactionalData(); ?>);
        })();
    </script>
<?php endif; ?>

