<?php
/** @var \Freshrelevance\Digitaldatalayer\Block\DdlProduct $block */
$data = $block->getDDLData();
?>
<?php if ($block->moduleEnabled()): ?>
    <script type="text/javascript">
        (function () {
            window.dod = (<?= $block->getDDLData(); ?>);
        })();
    </script>
<?php endif; ?>

<script type="text/javascript">
	require(['jquery', 'domReady!'], function ($) {
	<?php 
	echo $block->getProductDetailsFbJs();
	?>
	});
	</script>	
