<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$orderDatamodel = $objectManager->get('Magento\Sales\Model\Order')->getCollection()->getLastItem();
$urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');
$page_url = $urlInterface->getCurrentUrl();
$orderId   =   $orderDatamodel->getId();
$order = $objectManager->create('\Magento\Sales\Model\Order')->load($orderId);
$orderItems = $order->getAllItems();
$payment = $order->getPayment();
$method = $payment->getMethodInstance();
$methodTitle = $method->getCode();
$ship_method = $order->getShippingMethod();
$ord_id = $order->getIncrementId();
//exit;
$grand_total = $order->getGrandTotal();
$sku = "";
foreach ($orderItems as $item) {
   $product_name=   $item->getName();
   $sku .= $item->getSku().',';
}
$pro_sku = rtrim($sku, ',');
?>
<script type="text/javascript">
        (function () {
            window.dod = ({
    "page": {
        "pageInfo": {
            "pageName": "Confirmation Page",
            "destinationURL": "<?php echo $page_url; ?>"
            },
        "category": { "pageType": "Success" }
    },
    "cart": { "price": { "basePrice": <?php echo $grand_total; ?>} },
    "user": { "profile": [{ "profileInfo": { "language": "en_GB", "returningStatus": "true" } }] },
    "paymentMethod": "Card",
    "dealId": "<?php echo $pro_sku; ?>",
    "orderValue": <?php echo $grand_total; ?>,
    "orderid": "<?php echo $ord_id; ?>",
    "shippingmethod": "<?php echo $ship_method; ?>",
});
})();
    </script>
