<?php
/** @var \OnTap\Deal\Block\DealList $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Catalog\Model\Product $product */

/** @var \OnTap\Deal\ViewModel\SocialCue\TotalBought $totalBoughtCue */
$totalBoughtCue = $block->getTotalBought();

/** @var \OnTap\Deal\ViewModel\SocialCue\BusinessImage $businessImageCue */
$businessImageCue = $block->getBusinessImage();

/** @var \OnTap\Deal\ViewModel\SocialCue\SaveUpTo $saveUpToCue */
$saveUpToCue = $block->getSaveUpTo();

$type = 'left_column_product_list';
$image = 'left_column_list_image';
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$blockObj = $objectManager->get('Rvs\ExpiryProduct\Model\Grouplist');
$current_path = $blockObj->getCurrentpath();
if($current_path != 'index'){
//$collection = $block->getLeftLimitedProductCollection();
$collection = $blockObj->getProductCollectionFromCategoryLeft();
}else{
$collection = $blockObj->getLeftList();
}
?>
<?php //foreach ($block->getLeftLimitedProductCollection() as $product):
foreach ($collection as $product):
$pro_id = $product->getId();
$cats = $product->getCategoryIds();
         $firstCategoryId = "";
                                if(count($cats) ){

                                    if($cats[0]==2){
                                        $firstCategoryId = $cats[1];
                                    }
                                    else{
                                          $firstCategoryId = $cats[0];
                                    }
                                    }
	$product_url = $product->setCategoryId($firstCategoryId)->getProductUrl();
 ?>
    <div class="deals-side-container">
        <div class="deals-item deals-side-deal">
            <div class="deal deal-summary">
                <!-- Product Header section -->
                <div class="deal-header">
                    <h2><?= $escaper->escapeHtml($product->getName()) ?></h2>
                </div>

                <!-- Product Carousel section -->
                <div class="deal-imagery">
                    <a href="<?= $escaper->escapeUrl($product_url) ?>" class="product-image">
                        <?= $block->getImage($product, $image)->toHtml() ?>
                    </a>

                    <div class="deal-summary-main-price-splat">
                        <div class="deal-main-price-splat deal-main-price-splat-is-state-compact">
                            <div class="deal-main-price-splat-flex-wrapper">
                                <?= $block->getProductPriceHtml($product, $type) ?>
                            </div>
                        </div>
                    </div>

                    <?php if ($businessImageCue->canShow($product)): ?>
                        <div class="deal-summary-merchant-seal">
                            <div class="deal-merchant-seal">
                                <?php $website = $escaper->escapeUrl($businessImageCue->getWebAddressValue($product)); ?>
                                <?php if ($website): ?>
                                    <a href="<?= $website ?>" target="_blank">
                                        <img class="img-responsive"
                                             src="<?= $escaper->escapeUrl($businessImageCue->getImgValue($product)) ?>"
                                             alt="<?= $escaper->escapeHtml($businessImageCue->getAltValue($product)) ?>" />
                                    </a>
                                <?php else: ?>
                                    <img class="img-responsive"
                                         src="<?= $escaper->escapeUrl($businessImageCue->getImgValue($product)) ?>"
                                         alt="<?= $escaper->escapeHtml($businessImageCue->getAltValue($product)) ?>" />
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endif; ?>

                    <div class="overlay-overlays">
                        <div class="image-overlay-left">
                        </div>

                        <div class="image-overlay-right">
                        </div>
                    </div>
                </div>

                <!-- Product Status bar section -->
                <div class="deal-lead-status-bar deal-status-bar-is-hiding-merchant">
                    <div class="product-name-mobile"><?= $escaper->escapeHtml($product->getName()) ?></div>
                    <div class="deal-status-bar-wrapper">
                        <div class="deal-status-bar-item-merchant">
                            <img src="<?php echo $this->getViewFileUrl('images/3973197-logo.png'); ?>" alt="" width="161" height="73"/>
                        </div>

                        <?php if ($totalBoughtCue->canShow($product)): ?>
                            <div class="deal-status-bar-item deal-status-bar-item-stats">
                                <div class="deal-status-bar-label"><?php echo __('Bought') ?>+</div>
                                <div class="deal-status-bar-value">
                                    <?= $escaper->escapeHtml($totalBoughtCue->getValue($product)); ?>
                                </div>
                            </div>
                        <?php endif; ?>

                        <?php if ($saveUpToCue->canShow($product)): ?>
                            <div class="deal-status-bar-item deal-status-bar-item-stats">
                                <div class="deal-status-bar-label"><?php echo __('Save up to') ?></div>
                                <div class="deal-status-bar-value"><?= $saveUpToCue->getValue($product) ?></div>
                            </div>
                        <?php endif; ?>

                        <div class="deal-status-bar-item deal-status-bar-item-countdown">
							<?php
							$exipry_date = $product->getCountdownTimer();
							if($exipry_date != ''){
							?>
							<div class="deal-status-bar-label"><?php echo __('Time Remaining') ?></div>
							<div class="deal-status-bar-value small" id="race<?php echo $pro_id; ?>"></div>
							<?php } ?>    
                        </div>

                        <div class="deal-status-bar-item deal-status-bar-item-buttons">
                            <a class="secondary tocart" href="<?= $escaper->escapeUrl($product_url) ?>">
                                <span><?= __('View!') ?></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
        
<?php endforeach; ?>

<script>
// Set the date we're counting down to
var countdowns = [
<?php foreach ($collection as $product) {
$exipry_date = $product->getCountdownTimer();
$formated_date = substr($exipry_date, 0, -3);
$date_time = date('m/d/Y H:i:s', $formated_date);
$date_time_new = date('m/d/Y H:i:s', $formated_date);
$pro_id = $product->getId();
if($exipry_date != ''){
?>
  {
    id: <?php echo $product->getId() ?>,
    date: new Date("<?php echo date('M j, Y H:i:s', strtotime($date_time));?>").getTime()
    
  },
<?php } }?>
];

// Update the count down every 1 second
var timer = setInterval(function() {
  // Get todays date and time
  var now = Date.now();

  var index = countdowns.length - 1;

  // we have to loop backwards since we will be removing
  // countdowns when they are finished
  while(index >= 0) {
    var countdown = countdowns[index];

    // Find the distance between now and the count down date
    var distance = countdown.date - now;

    // Time calculations for days, hours, minutes and seconds
    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);

    var timerElement = document.getElementById("race" + countdown.id);

    // If the count down is over, write some text 
    if (distance < 0) {
	
	var date = new Date(countdown.date);
	var next_threedate = date.setDate(date.getDate() + 3);
    var distance = next_threedate - now;
     var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    if(days == 0){
      timerElement.innerHTML =  hours + "h " + minutes + "m " + seconds + "s ";
      }
      else{
      timerElement.innerHTML =  days + "d " + hours + "h " + minutes + "m " + seconds + "s ";
      }
      //console.log(countdown.id);
      // this timer is done, remove it
      //countdowns.splice(index, 1);
    } else {
    if(days == 0){
      timerElement.innerHTML =  hours + "h " + minutes + "m " + seconds + "s ";
      }
      else{
      timerElement.innerHTML =  days + "d " + hours + "h " + minutes + "m " + seconds + "s ";
      }
      //timerElement.innerHTML =  days + "D " + hours + "H " + minutes + "M ";
    }

    index -= 1;
  }

  // if all countdowns have finished, stop timer
  if (countdowns.length < 1) {
    clearInterval(timer);
  }
}, 1000);
</script>  
