<?php
/** @var \OnTap\Deal\Block\DealList $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Catalog\Model\Product $product */

/** @var \OnTap\Deal\ViewModel\SocialCue\TotalBought $totalBoughtCue */
$totalBoughtCue = $block->getTotalBought();

/** @var \OnTap\Deal\ViewModel\SocialCue\BusinessImage $businessImageCue */
$businessImageCue = $block->getBusinessImage();

/** @var \OnTap\Deal\ViewModel\SocialCue\SaveUpTo $saveUpToCue */
$saveUpToCue = $block->getSaveUpTo();

$type = 'right_column_product_list_large';
$image = 'right_column_list_large_image';

$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$blockObj = $objectManager->get('Rvs\ExpiryProduct\Model\Grouplist');
$current_path = $blockObj->getCurrentpath();
if($current_path == 'index'){
$collection = $block->getLimitedProductCollection();
}else{
$collection = $blockObj->getProductCollectionFromCategoryRight();
}

?>

<?php foreach ($collection as $product):
$pro_id = $product->getId();
$product_data = $objectManager->create('Magento\Catalog\Model\Product')->load($pro_id);
$exipry_date = $product_data['countdown_timer'];
$formated_date = substr($exipry_date, 0, -3);
$date_time = date('m/d/Y H:i:s', $formated_date);

 ?>
<div class="deals-item deals-secondary-deal">
    <!-- Product Header section -->
    <div class="deal-header">
        <h1><?= $escaper->escapeHtml($product->getName()) ?></h1>
        <h3><?= strip_tags($product->getShortDescription()) ?></h3>
    </div>

    <!-- Product Carousel section -->
    <div class="deal-lead-image-wrapper">
        <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>" class="product-image">
            <?= $block->getGalleryRenderer($product)->toHtml() ?>
        </a>
        <div class="deal-lead-main-price-splat">
            <div class="deal-main-price-splat">
                <div class="deal-main-price-splat-flex-wrapper">
                    <?= $block->getProductPriceHtml($product, $type) ?>
                </div>
            </div>
        </div>
    </div>

    <!-- Product Status bar section -->
    <div class="deal-lead-status-bar">
        <div class="product-name-mobile"><?= $escaper->escapeHtml($product->getName()) ?></div>
        <div class="deal-status-bar-wrapper">
            <?php if ($businessImageCue->canShow($product)): ?>
                <div class="deal-status-bar-item-merchant">
                    <?php $website = $escaper->escapeUrl($businessImageCue->getWebAddressValue($product)); ?>
                    <?php if ($website): ?>
                        <a href="<?= $website ?>" target="_blank">
                            <img src="<?= $escaper->escapeUrl($businessImageCue->getImgValue($product)) ?>"
                                 alt="<?= $escaper->escapeHtml($businessImageCue->getAltValue($product)) ?>" />
                        </a>
                    <?php else: ?>
                        <img src="<?= $escaper->escapeUrl($businessImageCue->getImgValue($product)) ?>"
                             alt="<?= $escaper->escapeHtml($businessImageCue->getAltValue($product)) ?>"/>
                    <?php endif; ?>
                </div>
            <?php endif; ?>

            <?php if ($totalBoughtCue->canShow($product)): ?>
                <div class="deal-status-bar-item deal-status-bar-item-stats">
                    <div class="deal-status-bar-label"><?php echo __('Bought') ?></div>
                    <div class="deal-status-bar-value">
                        <?= $escaper->escapeHtml($totalBoughtCue->getValue($product)); ?>
                    </div>
                </div>
            <?php endif; ?>

            <?php if ($saveUpToCue->canShow($product)): ?>
                <div class="deal-status-bar-item deal-status-bar-item-stats">
                    <div class="deal-status-bar-label"><?php echo __('Save up to') ?></div>
                    <div class="deal-status-bar-value"><?= $saveUpToCue->getValue($product) ?></div>
                </div>
            <?php endif; ?>

            <div class="deal-status-bar-item deal-status-bar-item-countdown">
            <?php
                        if($exipry_date != ''){
                        ?>
                        <div class="deal-status-bar-label"><?php echo __('Time Remaining') ?></div>
                        <div class="deal-status-bar-value large" id="race<?php echo $pro_id; ?>"></div>
                        <?php } ?>  
             </div>

            <div class="deal-status-bar-item deal-status-bar-item-buttons">
                <a class="secondary tocart" href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                    <span><?php echo __('View!') ?></span>
                </a>
            </div>
        </div>
    </div>
</div>
<?php endforeach; ?>

<script>
// Set the date we're counting down to
var countdownsL = [
<?php foreach ($collection as $product){
$pro_id = $product->getId();
$product_data = $objectManager->create('Magento\Catalog\Model\Product')->load($pro_id);
$exipry_date = $product_data['countdown_timer'];
$formated_date = substr($exipry_date, 0, -3);
$date_time = date('m/d/Y H:i:s', $formated_date);
$pro_id = $product->getId();
 if($exipry_date != ''){
?>
  {
    id: <?php echo $pro_id ?>,
    date: new Date("<?php echo date('M j, Y H:i:s', strtotime($date_time));?>").getTime()
  },
<?php } }?>
];

// Update the count down every 1 second
var timer = setInterval(function() {
  // Get todays date and time
  var now = Date.now();

  var index = countdownsL.length - 1;

  // we have to loop backwards since we will be removing
  // countdowns when they are finished
  while(index >= 0) {
    var countdown = countdownsL[index];

    // Find the distance between now and the count down date
    var distance = countdown.date - now;

    // Time calculations for days, hours, minutes and seconds
    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);

    var timerElement = document.getElementById("race" + countdown.id);

    // If the count down is over, write some text 
    if (distance < 0) {
      var date = new Date(countdown.date);
	var next_threedate = date.setDate(date.getDate() + 3);
    var distance = next_threedate - now;
     var days = Math.floor(distance / (1000 * 60 * 60 * 24));
    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
    if(days == 0){
      timerElement.innerHTML =  hours + "h " + minutes + "m " + seconds + "s ";
      }
      else{
      timerElement.innerHTML =  days + "d " + hours + "h " + minutes + "m " + seconds + "s ";
      }
      // this timer is done, remove it
      //countdownsL.splice(index, 1);
    } else {
    if(days == 0){
      timerElement.innerHTML =  hours + "h " + minutes + "m " + seconds + "s ";
      }
      else{
      timerElement.innerHTML =  days + "d " + hours + "h " + minutes + "m " + seconds + "s ";
      }
      //timerElement.innerHTML =  days + "D " + hours + "H " + minutes + "M ";
    }

    index -= 1;
  }

  // if all countdowns have finished, stop timer
  if (countdownsL.length < 1) {
    clearInterval(timer);
  }
}, 1000);
</script>  
