<?php
/**
 * Cordial/Magento Integration RFP
 *
 * @category    Cordial
 * @package     Cordial_Sync
 * @author      Cordial Team <info@cordial.com>
 * @copyright   Cordial (http://cordial.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

// @codingStandardsIgnoreFile
?>

<?php /* @var $block Cordial\Sync\Block\System\Config\Form\Field\CreateMapAttributes */ ?>

<?php echo $this->getButtonHtml(); ?>

    <script>
    //<![CDATA[
    function createMapAttributes() {
        new Ajax.Request('<?php echo $this->getAjaxUrl() ?>', {
            method: 'get',
            //parameters: {form_key: FORM_KEY},
            onSuccess: function (transport) {
                var response;
                try {
                    response = transport.responseJSON || transport.responseText.evalJSON(true) || {};
                    if (response.status == 'success') {
                        alert('<?php echo __('The map was successfully created.') ?>');
                    }
                    else {
                        if(response.message)
                            alert(response.message);
                        else
                            alert('<?php echo __('An error has occurred while creating map') ?>');
                    }
                } catch (e) {
                    response = {};
                }
            },
            onFailure: function () {
                alert('<?php echo __('Something went wrong.') ?>');
            }
        });
    }
    //]]>
</script>
