<?php
/**
 * Cordial/Magento Integration RFP
 *
 * @category    Cordial
 * @package     Cordial_Sync
 * @author      Cordial Team <info@cordial.com>
 * @copyright   Cordial (http://cordial.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

// @codingStandardsIgnoreFile
?>

<?php /* @var $this Cordial\Sync\Block\System\Config\Form\Field\TestButton */ ?>

<script type="text/javascript">
    //<![CDATA[
    function testTemplates() {

        if (!Validation.get('required-entry').test($('cordial_sync_general_email_test').getValue())){
            alert("<?php echo __('Email can\'t be blank.'); ?>");
            return false;
        }
        if (!Validation.get('validate-email').test($('cordial_sync_general_email_test').getValue())){
            alert("<?php echo __('Email address is not valid.'); ?>");
            return false;
        }

        params = {
            storeId : '<?php echo '1'; // Mage::helper('sync')->getCurrentConfigurationStoreId(); ?>',
            emails: $('cordial_sync_general_email_test').value
        }

        new Ajax.Request('<?php echo $this->getTestUrl() ?>', {
            parameters:     params,

            onSuccess: function(transport) {
                var response;

                try {
                    response = transport.responseJSON || transport.responseText.evalJSON(true) || {};
                    if (response.status == 'error'
                        && response.message
                    ) {
                        alert(response.message);
                    } else {
                        alert('<?php echo __('Sent. Please check email.') ?>');
                    }
                } catch (e) {
                    response = {};
                    alert('<?php echo __('Error. Please check logs.'); ?>');
                }
            }
        });
    }
    //]]>
</script>