<?php
/*
 * Copyright (c) On Tap Networks Limited.
 */
/**
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

?>
<div class="product-list-gallery gallery-placeholder _block-content-loading" data-gallery-role="product-gallery-<?= $block->getProductId() ?>">
    <img
        alt="main product photo"
        class="gallery-placeholder__image"
        src="<?= $mainImageData ?>"
    />
</div>
<script type="text/x-magento-init">
    {
        "[data-gallery-role=product-gallery-<?= $block->getProductId() ?>]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= $block->getMagnifier() ?>,
                "data": <?= $block->getGalleryImagesJson() ?>,
                "options": <?= $block->getGalleryOptions()->getOptionsJson() ?>,
                "fullscreen": <?= $block->getGalleryOptions()->getFSOptionsJson() ?>,
                "breakpoints": <?= $block->getBreakpoints() ?>
            }
        }
    }
</script>
